import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { createClient } from "@/lib/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  let role: string | null = null;
  if (user) {
    const { data: member } = await supabase
      .from("members")
      .select("role")
      .eq("user_id", user.id)
      .maybeSingle();
    role = member?.role ?? null;
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <header className="flex items-center justify-between border-b border-zinc-200 px-6 py-4 dark:border-zinc-800">
          <Link href="/" className="font-semibold text-black dark:text-zinc-50">
            Task System
          </Link>
          <nav className="flex items-center gap-4 text-sm text-zinc-700 dark:text-zinc-300">
            {user ? (
              <>
                <Link href="/tasks">My Tasks</Link>
                {role === "admin" && <Link href="/admin/tasks">Task Board</Link>}
                {role === "admin" && <Link href="/admin/members">Members</Link>}
                <form action="/auth/logout" method="POST">
                  <button type="submit" className="hover:underline">
                    Log out
                  </button>
                </form>
              </>
            ) : (
              <>
                <Link href="/login">Log in</Link>
                <Link href="/signup">Sign up</Link>
              </>
            )}
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
